///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace nln01
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxNeoLoad element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("a7c09f68-c6e2-4c56-9f2a-8ab32cc2fe0b")]
    public partial class RxNeoLoad : RepoGenBaseFolder
    {
        static RxNeoLoad instance = new RxNeoLoad();
        RxNeoLoadFolders.NewsORFAtAppFolder _newsorfat;

        /// <summary>
        /// Gets the singleton class instance representing the RxNeoLoad element repository.
        /// </summary>
        [RepositoryFolder("a7c09f68-c6e2-4c56-9f2a-8ab32cc2fe0b")]
        public static RxNeoLoad Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxNeoLoad() 
            : base("RxNeoLoad", "/", null, 0, false, "a7c09f68-c6e2-4c56-9f2a-8ab32cc2fe0b", ".\\RepositoryImages\\RxNeoLoada7c09f68.rximgres")
        {
            _newsorfat = new RxNeoLoadFolders.NewsORFAtAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a7c09f68-c6e2-4c56-9f2a-8ab32cc2fe0b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The NewsORFAt folder.
        /// </summary>
        [RepositoryFolder("7d953371-592c-4aee-9af2-95a7bfe0f5c3")]
        public virtual RxNeoLoadFolders.NewsORFAtAppFolder NewsORFAt
        {
            get { return _newsorfat; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class RxNeoLoadFolders
    {
        /// <summary>
        /// The NewsORFAtAppFolder folder.
        /// </summary>
        [RepositoryFolder("7d953371-592c-4aee-9af2-95a7bfe0f5c3")]
        public partial class NewsORFAtAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new NewsORFAt  folder.
            /// </summary>
            public NewsORFAtAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NewsORFAt", "/dom[@domain='orf.at']", parentFolder, 30000, null, false, "7d953371-592c-4aee-9af2-95a7bfe0f5c3", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7d953371-592c-4aee-9af2-95a7bfe0f5c3")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7d953371-592c-4aee-9af2-95a7bfe0f5c3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}